package com.example.instagramclonekt.model

data class Favourite(
    val img1:String,
    val img2:String,
    val img3:String,
    val img4:String,
    val img5:String,
    val img6:String,
    val img7:String,
    val img8:String,
    val img9:String,
    val img10:String,
    val img11:String,
    val img12:String,
    val img13:String,
    val img14:String,
    val img15:String,
    val img16:String,
    val img17:String,
    val img18:String,
    val img19:String,
    val img20:String,
    val img21:String,
    val img22:String,
    val img23:String,
    val img24:String,
    val img25:String,
    val img26:String,
    val img27:String,
    val img28:String,
    val img29:String,
)
